from Content import Content


def WriteDataBase(path: str) -> None:
    Content.WriteLine("using System;")
    Content.WriteLine("using System.Collections.Generic;")
    Content.WriteLine("using System.IO;")
    Content.WriteLine("using UnityEngine;")
    Content.WriteLine("namespace Config;")
    Content.StartBlock()
    Content.WriteLine("public class Vec3Vec")
    Content.StartBlock()
    Content.WriteLine("public int x = 0;")
    Content.WriteLine("public int y = 0;")
    Content.WriteLine("public int z = 0;")
    Content.EndBlock()
    Content.WriteLine("public class DataBase")
    Content.StartBlock()
    Content.WriteLine("#if UNITY_EDITOR || UNITY_STANDALONE_WIN ")
    Content.WriteLine("private static string DefaultFolder = Path.Combine(Application.streamingAssetsPath,""Bin/"");")
    Content.WriteLine("#elif  UNITY_IOS || UNITY_ANDROID")
    Content.WriteLine("private static string DefaultFolder = Path.Combine(Application.persistentDataPath,""Bin/"");")
    Content.WriteLine("#endif")
    Content.WriteLine("public static Stream OpenData(string fileName)")
    Content.StartBlock()
    Content.WriteLine("var filePath = DefaultFolder + fileName;")
    Content.WriteLine("#if UNITY_EDITOR || UNITY_STANDALONE_WIN || UNITY_IOS")
    Content.WriteLine("filePath = filePath.Replace(""file://"", "");")
    Content.WriteLine("#elif UNITY_ANDROID")
    Content.WriteLine("filePath = filePath.Replace(""file:///"", "");")
    Content.WriteLine("#endif")
    Content.WriteLine("return OpenFileStream(filePath);")
    Content.EndBlock()
    Content.WriteLine("public static System.IO.Stream OpenFileStream(string fullPath)")
    Content.StartBlock()
    Content.WriteLine("long streamLength = 0;")
    Content.WriteLine("return OpenFileStream(fullPath, out streamLength);")
    Content.EndBlock()
    Content.WriteLine("public static System.IO.Stream OpenFileStream(string fullPath, out long streamLength)")
    Content.StartBlock()
    Content.WriteLine("Stream filestream = null;")
    Content.WriteLine("streamLength = 0;")
    Content.WriteLine("try")
    Content.StartBlock()
    Content.WriteLine("filestream = File.OpenRead(fullPath);")
    Content.WriteLine("streamLength = filestream.Length;")
    Content.WriteLine("return filestream;")
    Content.EndBlock()
    Content.WriteLine("catch (Exception e)")
    Content.StartBlock()
    Content.WriteLine("filestream = null;")
    Content.WriteLine("UnityEngine.Debug.LogException(e);")
    Content.EndBlock()
    Content.WriteLine("return filestream;")
    Content.EndBlock()
    Content.WriteLine("public virtual void Load(BinaryReader pStream) { }")
    Content.WriteLine("public static void ReadIntList(BinaryReader pStream, ref List<int> intList)")
    Content.StartBlock()
    Content.WriteLine("int num = pStream.ReadInt16();")
    Content.WriteLine("for (int i = 0; i < num; i++)")
    Content.StartBlock()
    Content.WriteLine("if (intList == null)")
    Content.StartBlock()
    Content.WriteLine("intList = new List<int>();")
    Content.EndBlock()
    Content.WriteLine("intList.Add(pStream.ReadInt32());")
    Content.EndBlock()
    Content.EndBlock()
    Content.WriteLine(" public static void ReadShortList(BinaryReader pStream, ref List<short> intList)")
    Content.StartBlock()
    Content.WriteLine("int num = pStream.ReadInt16();")
    Content.WriteLine("for (int i = 0; i < num; i++)")
    Content.StartBlock()
    Content.WriteLine("if (intList == null)")
    Content.StartBlock()
    Content.WriteLine("intList = new List<short>();")
    Content.EndBlock()
    Content.WriteLine("intList.Add(pStream.ReadInt16());")
    Content.EndBlock()
    Content.EndBlock()
    Content.WriteLine("public static void ReadByteList(BinaryReader pStream, ref List<sbyte> intList)")
    Content.StartBlock()
    Content.WriteLine("int num = pStream.ReadInt16();")
    Content.WriteLine("for (int i = 0; i < num; i++)")
    Content.StartBlock()
    Content.WriteLine("if (intList == null)")
    Content.StartBlock()
    Content.WriteLine("intList = new List<sbyte>();")
    Content.EndBlock()
    Content.WriteLine("intList.Add(pStream.ReadSByte());")
    Content.EndBlock()
    Content.EndBlock()
    Content.WriteLine("public static void ReadFloatList(BinaryReader pStream, ref List<float> intList)")
    Content.StartBlock()
    Content.WriteLine("int num = pStream.ReadInt16();")
    Content.WriteLine("for (int i = 0; i < num; i++)")
    Content.StartBlock()
    Content.WriteLine("if (intList == null)")
    Content.StartBlock()
    Content.WriteLine("intList = new List<float>();")
    Content.EndBlock()
    Content.WriteLine("intList.Add(pStream.ReadSingle());")
    Content.EndBlock()
    Content.EndBlock()
    Content.WriteLine("public static void ReadStringList(BinaryReader pStream, ref List<string> strList)")
    Content.StartBlock()
    Content.WriteLine("int num = pStream.ReadInt16();")
    Content.WriteLine("for (int i = 0; i < num; i++)")
    Content.StartBlock()
    Content.WriteLine("if (strList == null)")
    Content.StartBlock()
    Content.WriteLine("strList = new List<string>();")
    Content.EndBlock()
    Content.WriteLine("strList.Add(pStream.ReadString());")
    Content.EndBlock()
    Content.EndBlock()
    Content.WriteLine("public static void ReadIntDictionary(BinaryReader pStream, ref Dictionary<int, int> intDictionary)")
    Content.StartBlock()
    Content.WriteLine("int num = pStream.ReadInt16();")
    Content.WriteLine("for (int i = 0; i < num; i++)")
    Content.StartBlock()
    Content.WriteLine("if (intDictionary == null)")
    Content.StartBlock()
    Content.WriteLine("intDictionary = new Dictionary<int, int>();")
    Content.EndBlock()
    Content.WriteLine("intDictionary[pStream.ReadInt32()] = pStream.ReadInt32();")
    Content.EndBlock()
    Content.EndBlock()
    Content.WriteLine("public static void ReadByteListList(BinaryReader pStream, ref List<List<sbyte>> intListList)")
    Content.StartBlock()
    Content.WriteLine("int listNum = pStream.ReadInt16();")
    Content.WriteLine("for (int i = 0; i < listNum; i++)")
    Content.StartBlock()
    Content.WriteLine("if (intListList == null)")
    Content.StartBlock()
    Content.WriteLine("intListList = new List<List<sbyte>>();")
    Content.EndBlock()
    Content.WriteLine("int intNum = pStream.ReadInt16();")
    Content.WriteLine("List<sbyte> intData = new List<sbyte>();")
    Content.WriteLine("for (int j = 0; j < intNum; j++)")
    Content.StartBlock()
    Content.WriteLine("intData.Add(pStream.ReadSByte());")
    Content.EndBlock()
    Content.WriteLine("intListList.Add(intData);")
    Content.EndBlock()
    Content.EndBlock()
    Content.WriteLine("public static void ReadShortListList(BinaryReader pStream, ref List<List<short>> intListList)")
    Content.StartBlock()
    Content.WriteLine("int listNum = pStream.ReadInt16();")
    Content.WriteLine("for (int i = 0; i < listNum; i++)")
    Content.StartBlock()
    Content.WriteLine("if (intListList == null)")
    Content.StartBlock()
    Content.WriteLine("intListList = new List<List<short>>();")
    Content.EndBlock()
    Content.WriteLine("int intNum = pStream.ReadInt16();")
    Content.WriteLine("List<short> intData = new List<short>();")
    Content.WriteLine("for (int j = 0; j < intNum; j++)")
    Content.StartBlock()
    Content.WriteLine("intData.Add(pStream.ReadInt16());")
    Content.EndBlock()
    Content.WriteLine("intListList.Add(intData);")
    Content.EndBlock()
    Content.EndBlock()
    Content.WriteLine("public static void ReadIntListList(BinaryReader pStream, ref List<List<int>> intListList)")
    Content.StartBlock()
    Content.WriteLine("int listNum = pStream.ReadInt16();")
    Content.WriteLine("for (int i = 0; i < listNum; i++)")
    Content.StartBlock()
    Content.WriteLine("if (intListList == null)")
    Content.StartBlock()
    Content.WriteLine("intListList = new List<List<int>>();")
    Content.EndBlock()
    Content.WriteLine("int intNum = pStream.ReadInt16();")
    Content.WriteLine("List<int> intData = new List<int>();")
    Content.WriteLine("for (int j = 0; j < intNum; j++)")
    Content.StartBlock()
    Content.WriteLine("intData.Add(pStream.ReadInt32());")
    Content.EndBlock()
    Content.WriteLine("intListList.Add(intData);")
    Content.EndBlock()
    Content.EndBlock()
    Content.WriteLine("public static void ReadFloatListList(BinaryReader pStream, ref List<List<float>> floatListList)")
    Content.StartBlock()
    Content.WriteLine("int listNum = pStream.ReadInt16();")
    Content.WriteLine("for (int i = 0; i < listNum; i++)")
    Content.StartBlock()
    Content.WriteLine("if (floatListList == null)")
    Content.StartBlock()
    Content.WriteLine("floatListList = new List<List<float>>();")
    Content.EndBlock()
    Content.WriteLine("int floatNum = pStream.ReadInt16();")
    Content.WriteLine("List<float> floatData = new List<float>();")
    Content.WriteLine("for (int j = 0; j < floatNum; j++)")
    Content.StartBlock()
    Content.WriteLine("floatData.Add(pStream.ReadSingle());")
    Content.EndBlock()
    Content.WriteLine("floatListList.Add(floatData);")
    Content.EndBlock()
    Content.EndBlock()
    Content.WriteLine("public object GetValue(string propertyName)")
    Content.StartBlock()
    Content.WriteLine("var info = this.GetType().GetProperty(propertyName);")
    Content.WriteLine("if (info != null)")
    Content.StartBlock()
    Content.WriteLine("return info.GetValue(this, null);")
    Content.EndBlock()
    Content.WriteLine("else")
    Content.StartBlock()
    Content.WriteLine("return null;")
    Content.EndBlock()
    Content.EndBlock()
    Content.WriteLine("public static void ReadVec3VecList(BinaryReader pStream, ref List<Vec3Vec> Vec3VecList)")
    Content.StartBlock()
    Content.WriteLine("int listNum = pStream.ReadInt16();")
    Content.WriteLine("if (Vec3VecList == null)")
    Content.StartBlock()
    Content.WriteLine("Vec3VecList = new List<Vec3Vec>();")
    Content.EndBlock()
    Content.WriteLine("for (int i = 0; i < listNum; ++i)")
    Content.StartBlock()
    Content.WriteLine("Vec3Vec data = new Vec3Vec();")
    Content.WriteLine("data.x = pStream.ReadInt32();")
    Content.WriteLine("data.y = pStream.ReadInt32();")
    Content.WriteLine("data.z = pStream.ReadInt32();")
    Content.WriteLine("Vec3VecList.Add(data);")
    Content.EndBlock()
    Content.EndBlock()
    Content.WriteLine("public static void ReadVec3Vec(BinaryReader pStream, ref Vec3Vec Vec3Vect)")
    Content.StartBlock()
    Content.WriteLine("if (Vec3Vect == null)")
    Content.StartBlock()
    Content.WriteLine("Vec3Vect = new Vec3Vec();")
    Content.EndBlock()
    Content.WriteLine("Vec3Vect.x = pStream.ReadInt32();")
    Content.WriteLine("Vec3Vect.y = pStream.ReadInt32();")
    Content.WriteLine("Vec3Vect.z = pStream.ReadInt32();")
    Content.EndBlock()
    Content.EndBlock()
    Content.EndBlock()
    Content.WriteFile(path)
